### ISSUE TITLE
Rat::Precise not on Raku.land

### ISSUE THREAD

**Issue by lizmat** [thundergnat/Rat-Precise#1]
The reason that `Rat::Precise` is not on Raku.land is because it is *not* on the zef ecosystem, and it is no longer in the p6c ecosystem either.

Installation is still possible, but that then occurs from the REA.

I suggest doing a version bump and another upload to zef ecosystem.

**Comment by thundergnat** [comment]
I plowed through about 20 modules back in December, migrating them all to zef. I think I just neglected to actually upload this one to zef at the time. Tried doing a mi6 release and it seemed to go ok. If it shows up on raku.land I'll be golden.

**Comment by thundergnat** [comment]
And it worked. Turns out things work a lot better if you actually do them. Whoda thunk?
