### ISSUE TITLE
Rework module to replace Rational.Str ?

### ISSUE THREAD

**Issue by lizmat** [thundergnat/Rat-Precise#2]
Would you be ok if I used your module as a base to rework as an alternative `Rational.Str` in a PR?

**Comment by thundergnat** [comment]
Absolutely.

**Comment by lizmat** [comment]
Ok, will do that tomorrow...  :-)

**Comment by lizmat** [comment]
For the record: I've come to the conclusion that losing about 15% of performance to get digit support in `Rational.Str` is not going to be worth it.  So I will rework this into explicit support for `Rational`s in the new `Formatter` class, which will be the base of the new `sprintf` and `.fmt` functionality.

**Comment by thundergnat** [comment]
That seems reasonable. Only pay the penalty when you explicitly need and ask for the extended precision.
